# Generated by Django 3.2.8 on 2022-01-17 13:24

import dashboard.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', dashboard.managers.DiscordUserOAuth2Manger()),
            ],
        ),
        migrations.CreateModel(
            name='Guilds',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guildID', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=255)),
                ('owner', models.BooleanField()),
            ],
        ),
    ]
