# Generated by Django 3.2.8 on 2022-01-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guilds',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
