# Generated by Django 3.2.8 on 2022-01-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_guilds_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotGuilds',
            fields=[
                ('guildID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=100)),
            ],
        ),
    ]
