# Generated by Django 3.2.8 on 2022-01-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_botguilds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotGuilds',
        ),
    ]
